settings:
  ecmascript: 6

env:
  browser: true
  jest: true

rules:
  quotes:
    - error
    - double
    - avoidEscape: true
  camelcase: 0
  arrow-parens: 0
  func-style: 0
  no-undef: "off"
  prefer-destructuring: 0
  prefer-object-spread: 1
  prefer-rest-params: 1
  prefer-const: 1
  prefer-promise-reject-errors: 0
  prefer-spread: 1
  lines-between-class-members: 0
  func-names: 0
  comma-dangle: 0
  spaced-comment: 0
  no-console: 2
  no-new: 0
  no-param-reassign: 0
  linebreak-style: 0
  object-shorthand: 0
  no-underscore-dangle: 0
  no-else-return: 0
  no-restricted-globals: 0
  no-unneeded-ternary: 1
  no-shadow: 1
  no-var: 1
  no-return-assign: 1
  no-extra-boolean-cast: 1
  no-empty-pattern: 0
  no-undef-init: 0
  no-unused-expressions: 1
  no-useless-return: 1
  no-nested-ternary: 0
  no-unreachable: 1
  no-irregular-whitespace: 0
  no-lonely-if: 0
  no-prototype-builtins: 0
  no-restricted-syntax: 0
  dot-notation: 0
  array-callback-return: 0
  max-classes-per-file: 0
  class-methods-use-this: 0
  radix: 1
  eqeqeq: 0
  default-case: 0
  consistent-return: 0
  import/named: 0
  import/no-dynamic-require: 0
  import/no-useless-path-segments: 1
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0
  import/extensions: 0
  import/prefer-default-export: 0
  import/order: 0
  import/no-cycle: 1
  import/first: 0
  import/no-mutable-exports: 0
  import/newline-after-import: 1
  import/no-duplicates: 1
  react/no-unused-state: 1
  react/no-children-prop: 1
  react/no-this-in-sfc: 1
  react/sort-comp: 0
  react/forbid-prop-types: 0
  react/no-unused-prop-types: 0
  react/prefer-stateless-function: 0
  react/require-default-props: 0
  react/default-props-match-prop-types: 0
  react/destructuring-assignment: [1, "always", { "ignoreClassFields": true }]
  react/no-access-state-in-setstate: 0
  react/no-did-mount-set-state: 0
  react-hooks/exhaustive-deps: 1
  react-hooks/rules-of-hooks: 1
  react/jsx-no-bind: 1
  react/jsx-no-duplicate-props: 1
  react/jsx-filename-extension: 0
  react/jsx-wrap-multilines: 0
  react/jsx-curly-brace-presence: 0
  react/jsx-props-no-spreading: 0
  react/jsx-fragments: 0
  react/jsx-boolean-value: 0
  react/no-array-index-key: 0
  react/no-did-update-set-state: 0
  react/no-deprecated: 1
  react/prop-types: 0
  react/static-property-placement: 0
  react/state-in-constructor: 0
  react/self-closing-comp: 0
  react/button-has-type: 0
  prefer-template: 0
  flowtype/generic-spacing: 0
  jsx-a11y/image-has-alt: 0
  jsx-a11y/label-has-for: 0
  jsx-a11y/anchor-is-valid: 0
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/no-noninteractive-tabindex: 0
  jsx-a11y/no-noninteractive-element-interactions: 0
  jsx-a11y/label-has-associated-control: 0
  jsx-a11y/mouse-events-have-key-events: 0
  jsx-a11y/alt-text: 0
  jsx-a11y/img-redundant-alt: 0
  jsx-a11y/control-has-associated-label: 0
  no-array-constructor: 0
  no-use-before-define: 0
  no-unused-vars: 0
